sonar.projectKey=SDMOgroup22
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.token=sqp_216068b4830bf314014800cd6eccc3bdaa89dc68